# based on:
# - .github/workflows/ci-test-node.js.yml
# - https://github.com/actions/starter-workflows/blob/b2e786d4e9af21f57ab07c1bc7231ed867f7675f/ci/node.js.yml

# skip multiple tests due to issue 42 ref:
# - https://github.com/react-recompose/react-recompose/issues/42
name: dist Rollup build - skip 2 tests

# FUTURE TODO refactor some more of these steps into script(s) that
# can be run from either the command line or GitHub CI.

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ext:
        - cjs.js
        - esm.js
        - umd.js
        # dist build test of Recompose.min.js is separated into min-dist-build-test.yml
        # due to the number of tests not working with Recompose.min.js

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version:
        - 14.x
        - 16.x
        - 18.x

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build:recompose:rollup
    - name: add (--dev) required dependencies
      # FUTURE TODO should install dependencies as specified src/packages/recompose/package.json
      run: yarn add --dev @babel/runtime change-emitter hoist-non-react-statics react-lifecycles-compat
    - name: copy __tests__ from src/packages/recompose
      run: cp -r src/packages/recompose/__tests__ lib/packages/recompose/dist
    - name: copy js files needed for some tests # TODO need a better solution, should be able to import from the bundle for most if not all tests
      run: |
        cp src/packages/recompose/*.js lib/packages/recompose/dist
        cp -r src/packages/recompose/utils lib/packages/recompose/dist
    - name: remove test(s) not working with dist build # TODO get all tests working with the dist build (issue 42)
      run: |
        rm lib/packages/recompose/dist/__tests__/mapPropsStream-test.js
        rm lib/packages/recompose/dist/__tests__/mapPropsStreamWithConfig-test.js # issue with Recompose.umd.js
        rm lib/packages/recompose/dist/__tests__/withStateHandlers-test.js # TODO NEEDS INVESTIGATION
    - run: cp lib/packages/recompose/dist/Recompose.${{ matrix.ext }} lib/packages/recompose/dist/index.js
    - run: yarn jest lib/packages/recompose/dist
