# based on:
# - .github/workflows/dist-build-test.yml
# - .github/workflows/ci-test-node.js.yml
# - https://github.com/actions/starter-workflows/blob/b2e786d4e9af21f57ab07c1bc7231ed867f7675f/ci/node.js.yml

# issue ref:
# - https://github.com/react-recompose/react-recompose/issues/42
name: min Rollup build - skip many tests see issue 42

# FUTURE TODO refactor some more of the steps into script(s) that
# can be run from either the command line or GitHub CI.

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version:
        - 14.x
        - 16.x
        os:
        - ubuntu-latest
        - macos-latest
        # FOR FUTURE CONSIDERATION:
        # - windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build:recompose:rollup
    - name: add (--dev) required dependencies
      # FUTURE TODO should install dependencies as specified src/packages/recompose/package.json
      run: yarn add --dev @babel/runtime change-emitter hoist-non-react-statics react-lifecycles-compat
    - name: copy __tests__ from src/packages/recompose
      run: cp -r src/packages/recompose/__tests__ lib/packages/recompose/dist
    - name: copy js files needed for some tests # TODO need a better solution, should be able to import from the bundle for most if not all tests
      run: |
        cp src/packages/recompose/*.js lib/packages/recompose/dist
        cp -r src/packages/recompose/utils lib/packages/recompose/dist
    - name: remove tests not working with Recompose.min.js # # TODO improve as discussed in issue 42
      run: |
        rm lib/packages/recompose/dist/__tests__/withHandlers-test.js
        rm lib/packages/recompose/dist/__tests__/mapPropsStream-test.js
        rm lib/packages/recompose/dist/__tests__/withStateHandlers-test.js
        rm lib/packages/recompose/dist/__tests__/withState-test.js
        rm lib/packages/recompose/dist/__tests__/pure-test.js
        rm lib/packages/recompose/dist/__tests__/mapPropsStreamWithConfig-test.js
        rm lib/packages/recompose/dist/__tests__/onlyUpdateForPropTypes-test.js
        rm lib/packages/recompose/dist/__tests__/withReducer-test.js
        rm lib/packages/recompose/dist/__tests__/withPropsOnChange-test.js
        rm lib/packages/recompose/dist/__tests__/branch-test.js
        rm lib/packages/recompose/dist/__tests__/shouldUpdate-test.js
        rm lib/packages/recompose/dist/__tests__/lifecycle-test.js
        rm lib/packages/recompose/dist/__tests__/onlyUpdateForKeys-test.js
        rm lib/packages/recompose/dist/__tests__/renameProps-test.js
        rm lib/packages/recompose/dist/__tests__/withContext-test.js
        rm lib/packages/recompose/dist/__tests__/fromRenderProps-test.js
        rm lib/packages/recompose/dist/__tests__/defaultProps-test.js
        rm lib/packages/recompose/dist/__tests__/mapProps-test.js
        rm lib/packages/recompose/dist/__tests__/renderNothing-test.js
        rm lib/packages/recompose/dist/__tests__/renameProp-test.js
        rm lib/packages/recompose/dist/__tests__/withProps-test.js
        rm lib/packages/recompose/dist/__tests__/flattenProp-test.js
        rm lib/packages/recompose/dist/__tests__/nest-test.js
        rm lib/packages/recompose/dist/__tests__/toRenderProps-test.js
    - run: cp lib/packages/recompose/dist/Recompose.min.js lib/packages/recompose/dist/index.js
    - run: yarn jest lib/packages/recompose/dist
