# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# based on:
# - .github/workflows/ci-test-node.js.yml
# - .github/workflows/test-react-16.yml
# - https://github.com/actions/starter-workflows/blob/b2e786d4e9af21f57ab07c1bc7231ed867f7675f/ci/node.js.yml

name: Preact - limited testing see issue 41

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn add --dev react@npm:@preact/compat react-dom@npm:@preact/compat enzyme-adapter-react-16@npm:enzyme-adapter-preact-pure preact@latest
    - run: npx cross-env TEST_WITH_PREACT=1 jest
