# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
# based on: https://github.com/actions/starter-workflows/blob/b2e786d4e9af21f57ab07c1bc7231ed867f7675f/ci/node.js.yml

name: test min dist build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: yarn build:recompose
    - run: yarn add --dev @babel/runtime change-emitter hoist-non-react-statics react-lifecycles-compat
    - run: cp src/packages/recompose/*.js lib/packages/recompose/dist
    - run: cp -r src/packages/recompose/utils lib/packages/recompose/dist
    - run: cp -r src/packages/recompose/__tests__ lib/packages/recompose/dist
    - run: cp lib/packages/recompose/dist/Recompose.min.js lib/packages/recompose/dist/index.js
    - run: yarn jest lib/packages/recompose/dist
